spring:
  application:
    name: scrabble-solver-service
  http:
    converters:
      preferred-json-mapper: jsonb
  jersey:
    type: filter

info:
  version: 1.0.0-SNAPSHOT

server:
  http2:
    enabled: true
  port: 8080
  shutdown: graceful
  servlet:
    application-display-name: "Scrabble Solver Service"
    register-default-servlet: true

